config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', registration: 'register', sign_up: 'cmon_let_me_in' }
  
  resources :orders, only: [:index, :update, :destroy]
  resource  :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]
  
  resources :categories do
    collection do
      post :rebuild
    end
  end

  resources :units
  resources :brands
  resources :products do
    resources :details
  end
  resources :sales


  
  root to: 'static#home'
  get '/dashboard' => 'static#dashboard'
  get '/setting'=>'static#setting'
  # get '/categories/:category' => 'static#products_by_category', as: 'products_by_category'
  
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord

  validates :name, presence: true
  has_many :product

end

app/models/category.rb
class Category < ApplicationRecord
	acts_as_nested_set
	extend FriendlyId
	friendly_id :title, use: :slugged

  	has_many :products
end

app/models/order.rb
class Order < ApplicationRecord
	has_many :order_items

	before_save :update_subtotal

  	def subtotal
    	order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
  	end
  
	private
	  def update_subtotal
	    self[:subtotal] = subtotal
	  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :unit_price, numericality: true, presence: true
  validate :product_present
  # validate :order_present

  before_save :finalize


  scope :today, lambda {where(created_at: Date.today.beginning_of_day..Date.today.end_of_day)}
  scope :current_week, lambda {where(created_at: Date.today.beginning_of_week.beginning_of_day..Date.today.end_of_week.end_of_day)}
  scope :last_week, lambda {where(created_at: Date.today.last_week.beginning_of_week.beginning_of_day..Date.today.last_week.end_of_week.end_of_day)}

  scope :current_month, lambda {where(created_at: Date.today.beginning_of_month.beginning_of_day..Date.today.end_of_month.end_of_day)}
  scope :last_month, lambda {where(created_at: Date.today.last_month.beginning_of_month.beginning_of_day..Date.today.last_month.end_of_month.end_of_day)}

  # scope :current_month_sales_rate, lambda {OrderItem.current_month.count*100/Product.sum(:quantity) if Product.sum(:quantity)>0}
  # scope :weekly_sales_rate_of_current_month, lambda {OrderItem.current_week.count*100/OrderItem.current_month.count if OrderItem.current_month.count>0}

  

  def self.current_month_sales_rate
    if Product.sum(:quantity)>0
      self.current_month.count*100/Product.sum(:quantity) 
    else
      0
    end
  end

  def self.weekly_sales_rate_of_current_month
    if OrderItem.current_month.count>0
      self.current_week.count*100/OrderItem.current_month.count 
    else
      0
    end
  end


  # @weekly_top_sales = OrderItem.current_week.group(:product_id).order('sum_quantity desc').sum(:quantity)
  #   @monthly_top_sales = OrderItem.current_month.group(:product_id).order('sum_quantity desc').sum(:quantity)


  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.unit_price
    end
  end

  def total_price
    unit_price * quantity
  end

	private
	  def product_present
	    if product.nil?
	      errors.add(:product, "is not valid or is not active.")
	    end
	  end

	  # def order_present
	  #   if order.nil?
	  #     errors.add(:order, "is not a valid order.")
	  #   end
	  # end

	  def finalize
	    self[:unit_price] = unit_price
	    self[:total_price] = quantity * self[:unit_price]
	  end
end

app/models/product.rb
class Product < ApplicationRecord
	belongs_to :category
	belongs_to :unit
	belongs_to :brand
	has_many :product_details, :dependent => :destroy
	has_many :order_items

	before_destroy :destroy_details

	extend FriendlyId
	friendly_id :name, use: :slugged

	validates :product_code, presence: true, uniqueness: true
	validates :name, presence: true
	validates :category_id, presence: true
	validates :unit_id, presence: true
	validates :brand_id, presence: true
	validates :unit_price, presence: true, numericality: true

	def self.search(search)
		where('name LIKE ? ', "%#{search}%")
	end

	def self.search_by_category(category, search)
		category.products.where('name LIKE ? ', "%#{search}%")
	end

	private
		def destroy_details
			self.product_details.delete_all
		end
end

app/models/product_detail.rb
class ProductDetail < ApplicationRecord
	belongs_to :product
	
	validates :quantity, presence: true
	validates :purchase_price, presence: true, numericality: true
end

app/models/unit.rb
class Unit < ApplicationRecord
	validates :name, presence: true
	has_many :product
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
	def create
		@brand = Brand.create(brand_params)
	end

	def edit
		@brand = Brand.find(params[:id])
	end

	def update
		@brand = Brand.find(params[:id])
		@brand.update_attributes(brand_params)
	end

	def destroy
		@brand = Brand.find(params[:id])
		@brand.destroy
	end


	private
		def brand_params
			params.require(:brand).permit(:name)
		end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
  	@order_items = current_order.order_items
  end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
	layout 'dashboard'

	def index
		# search = params[:search] if params[:search].present?
		start_date 	= params[:start_date].to_date.beginning_of_day if params[:start_date].present?
		end_date = params[:end_date].to_date.end_of_day if params[:end_date].present?
		
		if start_date.present? && end_date.present?
			@sales = OrderItem.where(created_at: start_date..end_date).order(created_at: :desc).paginate(page: params[:page], per_page: 10)
		else
			@sales = OrderItem.order(created_at: :desc).paginate(page: params[:page], per_page: 10)
		end
		
	end


end

app/controllers/units_controller.rb
class UnitsController < ApplicationController

	def create
		@unit = Unit.create(unit_params)
	end

	def edit
		@unit = Unit.find(params[:id])
	end

	def update
		@unit = Unit.find(params[:id])
		@unit.update_attributes(unit_params)
	end

	def destroy
		@unit = Unit.find(params[:id])
		@unit.destroy
	end


	private
		def unit_params
			params.require(:unit).permit(:name)
		end

end

app/helpers/application_helper.rb
module ApplicationHelper

	def active_class(link_path)
	  current_page?(link_path) ? "active" : ""
	end

	def categories
	  @categories = Category.roots
	end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/brands/_brand.html.erb
<% Brand.all.each do |brand| %>
    <li class="sortable-item ui-sortable-handle"> 
        <div style="float:left;" class="todo-actions">
            <div class="wrapper-actions">
                <div style="float:left">
                    <%= link_to edit_brand_path(brand), remote: true do %>
                        <span class="fa fa-square-o bg-success padding-top-12 btn-todo-check" data-toggle="modal" data-target="#modal-add-brand" style="width:40px; height:40px;"></span>
                    <% end %>
                    
                </div>
                <div style="float:right;">
                    <%= link_to brand_path(brand), remote: true, data: {:confirm => 'Are you sure?'}, :method => :delete do %>
                        <span class="fa fa-times bg-danger padding-top-12 btn-todo-remove" style="width:40px; height:40px;"></span>
                    <% end %>
                    
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
        <div style="float:right; float:left" class="todo-title">
            <span><%= brand.name %></span>
        </div>
        <div class="clearfix"></div>
    </li>
<% end %>

app/views/brands/_form.html.erb
<%= form_for @brand, remote: true do |f| %>
  
    <div class="modal-body">
        <div class="form-group">
            <%= f.label :name, "Name" %>
            <%= f.text_field :name, class: "form-control txtTitleTodo"  %>
        </div>
    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-default btn-warning btn-raised rippler rippler-default" data-dismiss="modal">Close</button>
      <%= f.submit "Save", class: "btn btn-primary btn-raised rippler rippler-default btn-save-new-task"  %>
    </div>
<% end %>

app/views/brands/create.js.erb
$("#brand").html("<%= escape_javascript(render 'brand') %>")
$('.txtTitleTodo').val('')

app/views/brands/destroy.js.erb
$("#brand").html("<%= escape_javascript(render 'brand') %>")

app/views/brands/edit.js.erb
$(".modal-content").html("<%= escape_javascript(render 'form') %>")

app/views/brands/update.js.erb
$("#brand").html("<%= escape_javascript(render 'brand') %>")
window.location.reload();
$('#modal-add-brand').modal('hide').empty();

app/views/units/_form.html.erb
<%= form_for @unit, remote: true do |f| %>
  
    <div class="modal-body">
        <div class="form-group">
            <%= f.label :name, "Name" %>
            <%= f.text_field :name, class: "form-control txtTitleTodo"  %>
        </div>
    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-default btn-warning btn-raised rippler rippler-default" data-dismiss="modal">Close</button>
      <%= f.submit "Save", class: "btn btn-primary btn-raised rippler rippler-default btn-save-new-task"  %>
    </div>
<% end %>

app/views/units/_unit.html.erb
<% Unit.all.each do |unit| %>
    <li class="sortable-item ui-sortable-handle"> 
        <div style="float:left;" class="todo-actions">
            <div class="wrapper-actions">
                <div style="float:left">
                    <%= link_to edit_unit_path(unit), remote: true do %>
                        <span class="fa fa-square-o bg-success padding-top-12 btn-todo-check" data-toggle="modal" data-target="#modal-add-unit" style="width:40px; height:40px;"></span>
                    <% end %>
                    
                </div>
                <div style="float:right;">
                    <%= link_to unit_path(unit), remote: true, data: {:confirm => 'Are you sure?'}, :method => :delete do %>
                        <span class="fa fa-times bg-danger padding-top-12 btn-todo-remove" style="width:40px; height:40px;"></span>
                    <% end %>
                    
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
        <div style="float:right; float:left" class="todo-title">
            <span><%= unit.name %></span>
        </div>
        <div class="clearfix"></div>
    </li>
<% end %>

app/views/units/create.js.erb
$("#unit").html("<%= escape_javascript(render 'unit') %>")
$('.txtTitleTodo').val('')

// $("#unit").hide()

// $(".btn-warning").click();
// $('#modal-add-unit').modal('toggle');
// $('#modal-add-todo .close').click()

app/views/units/destroy.js.erb
$("#unit").html("<%= escape_javascript(render 'unit') %>")

app/views/units/edit.js.erb
$(".modal-content").html("<%= escape_javascript(render 'form') %>")

app/views/units/update.js.erb
$("#unit").html("<%= escape_javascript(render 'unit') %>")
window.location.reload();
$('#modal-add-unit').modal('hide').empty();