config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', registration: 'register', sign_up: 'cmon_let_me_in' }
  
  resources :orders, only: [:index, :update, :destroy]
  resource  :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]
  
  resources :categories do
    collection do
      post :rebuild
    end
  end

  resources :units
  resources :brands
  resources :products do
    resources :details
  end
  resources :sales


  
  root to: 'static#home'
  get '/dashboard' => 'static#dashboard'
  get '/setting'=>'static#setting'
  # get '/categories/:category' => 'static#products_by_category', as: 'products_by_category'
  
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord

  validates :name, presence: true
  has_many :product

end

app/models/category.rb
class Category < ApplicationRecord
	acts_as_nested_set
	extend FriendlyId
	friendly_id :title, use: :slugged

  	has_many :products
end

app/models/order.rb
class Order < ApplicationRecord
	has_many :order_items

	before_save :update_subtotal

  	def subtotal
    	order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
  	end
  
	private
	  def update_subtotal
	    self[:subtotal] = subtotal
	  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :unit_price, numericality: true, presence: true
  validate :product_present
  # validate :order_present

  before_save :finalize


  scope :today, lambda {where(created_at: Date.today.beginning_of_day..Date.today.end_of_day)}
  scope :current_week, lambda {where(created_at: Date.today.beginning_of_week.beginning_of_day..Date.today.end_of_week.end_of_day)}
  scope :last_week, lambda {where(created_at: Date.today.last_week.beginning_of_week.beginning_of_day..Date.today.last_week.end_of_week.end_of_day)}

  scope :current_month, lambda {where(created_at: Date.today.beginning_of_month.beginning_of_day..Date.today.end_of_month.end_of_day)}
  scope :last_month, lambda {where(created_at: Date.today.last_month.beginning_of_month.beginning_of_day..Date.today.last_month.end_of_month.end_of_day)}

  # scope :current_month_sales_rate, lambda {OrderItem.current_month.count*100/Product.sum(:quantity) if Product.sum(:quantity)>0}
  # scope :weekly_sales_rate_of_current_month, lambda {OrderItem.current_week.count*100/OrderItem.current_month.count if OrderItem.current_month.count>0}

  

  def self.current_month_sales_rate
    if Product.sum(:quantity)>0
      self.current_month.count*100/Product.sum(:quantity) 
    else
      0
    end
  end

  def self.weekly_sales_rate_of_current_month
    if OrderItem.current_month.count>0
      self.current_week.count*100/OrderItem.current_month.count 
    else
      0
    end
  end


  # @weekly_top_sales = OrderItem.current_week.group(:product_id).order('sum_quantity desc').sum(:quantity)
  #   @monthly_top_sales = OrderItem.current_month.group(:product_id).order('sum_quantity desc').sum(:quantity)


  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.unit_price
    end
  end

  def total_price
    unit_price * quantity
  end

	private
	  def product_present
	    if product.nil?
	      errors.add(:product, "is not valid or is not active.")
	    end
	  end

	  # def order_present
	  #   if order.nil?
	  #     errors.add(:order, "is not a valid order.")
	  #   end
	  # end

	  def finalize
	    self[:unit_price] = unit_price
	    self[:total_price] = quantity * self[:unit_price]
	  end
end

app/models/product.rb
class Product < ApplicationRecord
	belongs_to :category
	belongs_to :unit
	belongs_to :brand
	has_many :product_details, :dependent => :destroy
	has_many :order_items

	before_destroy :destroy_details

	extend FriendlyId
	friendly_id :name, use: :slugged

	validates :product_code, presence: true, uniqueness: true
	validates :name, presence: true
	validates :category_id, presence: true
	validates :unit_id, presence: true
	validates :brand_id, presence: true
	validates :unit_price, presence: true, numericality: true

	def self.search(search)
		where('name LIKE ? ', "%#{search}%")
	end

	def self.search_by_category(category, search)
		category.products.where('name LIKE ? ', "%#{search}%")
	end

	private
		def destroy_details
			self.product_details.delete_all
		end
end

app/models/product_detail.rb
class ProductDetail < ApplicationRecord
	belongs_to :product
	
	validates :quantity, presence: true
	validates :purchase_price, presence: true, numericality: true
end

app/models/unit.rb
class Unit < ApplicationRecord
	validates :name, presence: true
	has_many :product
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
  	@order_items = current_order.order_items
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	layout 'dashboard', except: [:show]
	before_action :set_category, only: [:edit, :update, :show, :destroy]

	def index
		@categories = Category.roots
	end

	def new
		@category = Category.new
	end

	def create
		@category = Category.new(category_params)
		if @category.save
			flash[:success] = "Category has saved!"
			redirect_to categories_path			
		else
			render 'new'
		end
	end

	def show
		@order_item = current_order.order_items.new
		@products = @category.products
		if params[:search].present?
			@products = Product.search_by_category(@category, params[:search])
		end
	end

	def edit
		
	end

	def update
		if @category.update_attributes(category_params)
			flash[:success] = "Category has been updated!"
			redirect_to categories_path
		else
			render 'edit'
		end
	end

	def destroy
		
	end


	private
		def category_params
			params.require(:category).permit(:title, :parent_id)
		end

		def set_category
			@category = Category.friendly.find(params[:id])
		end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
	layout 'dashboard'

	def index
		# search = params[:search] if params[:search].present?
		start_date 	= params[:start_date].to_date.beginning_of_day if params[:start_date].present?
		end_date = params[:end_date].to_date.end_of_day if params[:end_date].present?
		
		if start_date.present? && end_date.present?
			@sales = OrderItem.where(created_at: start_date..end_date).order(created_at: :desc).paginate(page: params[:page], per_page: 10)
		else
			@sales = OrderItem.order(created_at: :desc).paginate(page: params[:page], per_page: 10)
		end
		
	end


end

app/controllers/units_controller.rb
class UnitsController < ApplicationController

	def create
		@unit = Unit.create(unit_params)
	end

	def edit
		@unit = Unit.find(params[:id])
	end

	def update
		@unit = Unit.find(params[:id])
		@unit.update_attributes(unit_params)
	end

	def destroy
		@unit = Unit.find(params[:id])
		@unit.destroy
	end


	private
		def unit_params
			params.require(:unit).permit(:name)
		end

end

app/helpers/application_helper.rb
module ApplicationHelper

	def active_class(link_path)
	  current_page?(link_path) ? "active" : ""
	end

	def categories
	  @categories = Category.roots
	end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
	<div class="form-group has-success">
		<div class="col-md-6 col-md-offset-3">
			<%= render 'shared/error', object: f.object %>
		</div>
	</div>
	<div class="form-group">
		<%= f.label :title, "Name" %>
		<%= f.text_field :title, class: 'form-control' %>
	</div>

	<div class="form-group">
		<%= f.label :parent_id %>
		<%= f.select :parent_id, nested_set_options(Category, @category) {|i| "#{sanitize('&nbsp;') * i.level} #{i.title}"}, include_blank: 'Select an item' %>
	</div>

	<%= f.submit "Save", class: 'btn btn-success' %>
<% end %>
  

app/views/categories/_item.html.erb
<li><%= set.name %>
<% unless set.leaf? %>
<ul>
  <%= render :partial => 'item', :collection => @set.select{|i| i.parent_id == set.id} %>
</ul>
<% end %>
</li>

app/views/categories/_tree.html.erb
<%= content_tag :li, class: 'sortable-item ui-sortable-handle', :id => dom_id(category) do %>
  
  	
  	<div style="float:right; float:left" class="todo-title">
  	    <span class="handle"><%= category.title %></span>
  	</div>
  	<div class="clearfix"></div>
      
	  <%= content_tag :ol, class: 'nested_style' do %>
	   <% for child in category.children do %>
	    <%= render :partial => "tree", :locals => {:category => child }%>
	   <% end %>
	  <% end unless category.leaf? %>
 <% end %>

app/views/categories/index.html.erb
<div class="row">

    <div class="col-md-12 col-sm-12 col-xs-12">

        <div class="widget">
            <div class="widget-header bg-white">
                <h3 class="fg-gray">Category</h3>
                <%= link_to(new_category_path) do  %>
                	<span class="fa fa-plus fg-gray pull-right btn-todo-add" ></span>
                <% end %>
                <div class="clearfix"></div>
            </div>
            <div class="widget-content bg-white">
                
                <div class="todo-list">
                    <ul class="sortable-container ui-sortable" style="overflow-y: hidden; outline: none;" tabindex="5008">

                    	

                    	<% @categories.each do |category| %>
                    		<%= render :partial => "tree", :locals => {:category => category} %> 
                    	<% end %>

                    	

                    </ul>

                    
                    

                </div><!--/todo-list-->

            </div><!--/widget-content--> 
            <div class="widget-footer padding-10 text-center">
                <a href="http://lancecoder.com/themes/thema/versions/html/index.php#">View all <i class="fa fa-arrow-right"></i></a>
            </div>
        </div><!--/widget-->

    </div>

</div><!--/.row-->

app/views/categories/new.html.erb
<h2>Create new category</h2>

<%= render 'form' %>

app/views/categories/show.html.erb
<div class="row">
  <div class="col-md-12">

    <div class="c_panel">

        <div class="c_title">
            <h2>Search Results Page</h2>
            <div class="clearfix"></div>
        </div><!--/.c_title-->

        <div class="c_content page-search-results">
            
            <div class="search-box">
              <%= form_tag(category_path(@category), method: 'get', id: 'search-products-by-category') do  %>
                <div class="input-group margin-bottom-15">
                    <%= text_field_tag :search, params[:search], class: 'form-control', placeholder: "Search Products" %>
                    <span class="input-group-btn">
                      <%= button_tag("Search", class: 'btn btn-success') %>
                    </span>
                </div>
              <% end %>
            </div>

            <div class="search-results">
              <div class="tab-content">
                  <div class="tab-pane fade in active" id="products-by-category">

                    <% @products.each do |product| %>
                      <%= render "static/item", product: product, order_item: @order_item %>
                    <% end %>
                    
                  </div>                    
              </div>
              <!--TAB END-->
            </div>
        </div><!--/.c_content-->
    </div><!--/.c_panels-->
  </div>
</div>