config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', registration: 'register', sign_up: 'cmon_let_me_in' }
  
  resources :orders, only: [:index, :update, :destroy]
  resource  :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]
  
  resources :categories do
    collection do
      post :rebuild
    end
  end

  resources :units
  resources :brands
  resources :products do
    resources :details
  end
  resources :sales


  
  root to: 'static#home'
  get '/dashboard' => 'static#dashboard'
  get '/setting'=>'static#setting'
  # get '/categories/:category' => 'static#products_by_category', as: 'products_by_category'
  
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord

  validates :name, presence: true
  has_many :product

end

app/models/category.rb
class Category < ApplicationRecord
	acts_as_nested_set
	extend FriendlyId
	friendly_id :title, use: :slugged

  	has_many :products
end

app/models/order.rb
class Order < ApplicationRecord
	has_many :order_items

	before_save :update_subtotal

  	def subtotal
    	order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
  	end
  
	private
	  def update_subtotal
	    self[:subtotal] = subtotal
	  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :unit_price, numericality: true, presence: true
  validate :product_present
  # validate :order_present

  before_save :finalize


  scope :today, lambda {where(created_at: Date.today.beginning_of_day..Date.today.end_of_day)}
  scope :current_week, lambda {where(created_at: Date.today.beginning_of_week.beginning_of_day..Date.today.end_of_week.end_of_day)}
  scope :last_week, lambda {where(created_at: Date.today.last_week.beginning_of_week.beginning_of_day..Date.today.last_week.end_of_week.end_of_day)}

  scope :current_month, lambda {where(created_at: Date.today.beginning_of_month.beginning_of_day..Date.today.end_of_month.end_of_day)}
  scope :last_month, lambda {where(created_at: Date.today.last_month.beginning_of_month.beginning_of_day..Date.today.last_month.end_of_month.end_of_day)}

  # scope :current_month_sales_rate, lambda {OrderItem.current_month.count*100/Product.sum(:quantity) if Product.sum(:quantity)>0}
  # scope :weekly_sales_rate_of_current_month, lambda {OrderItem.current_week.count*100/OrderItem.current_month.count if OrderItem.current_month.count>0}

  

  def self.current_month_sales_rate
    if Product.sum(:quantity)>0
      self.current_month.count*100/Product.sum(:quantity) 
    else
      0
    end
  end

  def self.weekly_sales_rate_of_current_month
    if OrderItem.current_month.count>0
      self.current_week.count*100/OrderItem.current_month.count 
    else
      0
    end
  end


  # @weekly_top_sales = OrderItem.current_week.group(:product_id).order('sum_quantity desc').sum(:quantity)
  #   @monthly_top_sales = OrderItem.current_month.group(:product_id).order('sum_quantity desc').sum(:quantity)


  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.unit_price
    end
  end

  def total_price
    unit_price * quantity
  end

	private
	  def product_present
	    if product.nil?
	      errors.add(:product, "is not valid or is not active.")
	    end
	  end

	  # def order_present
	  #   if order.nil?
	  #     errors.add(:order, "is not a valid order.")
	  #   end
	  # end

	  def finalize
	    self[:unit_price] = unit_price
	    self[:total_price] = quantity * self[:unit_price]
	  end
end

app/models/product.rb
class Product < ApplicationRecord
	belongs_to :category
	belongs_to :unit
	belongs_to :brand
	has_many :product_details, :dependent => :destroy
	has_many :order_items

	before_destroy :destroy_details

	extend FriendlyId
	friendly_id :name, use: :slugged

	validates :product_code, presence: true, uniqueness: true
	validates :name, presence: true
	validates :category_id, presence: true
	validates :unit_id, presence: true
	validates :brand_id, presence: true
	validates :unit_price, presence: true, numericality: true

	def self.search(search)
		where('name LIKE ? ', "%#{search}%")
	end

	def self.search_by_category(category, search)
		category.products.where('name LIKE ? ', "%#{search}%")
	end

	private
		def destroy_details
			self.product_details.delete_all
		end
end

app/models/product_detail.rb
class ProductDetail < ApplicationRecord
	belongs_to :product
	
	validates :quantity, presence: true
	validates :purchase_price, presence: true, numericality: true
end

app/models/unit.rb
class Unit < ApplicationRecord
	validates :name, presence: true
	has_many :product
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
  	@order_items = current_order.order_items
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def active_class(link_path)
	  current_page?(link_path) ? "active" : ""
	end

	def categories
	  @categories = Category.roots
	end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Inventory" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="front-header navbar navbar-default fixed-top navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Inventory", root_path, class: "navbar-brand", "data-turbolinks" => "false" %>
        <div class="navbar-collapse collapse navbar-responsive-collapse"> 
          <div class="top-nav">
          <ul class="nav navbar-nav">
            
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li class="cart-text"><%= render 'layouts/partials/cart_text' %></li> 
            <% if user_signed_in? %>
              <li><%= link_to 'Log out', destroy_user_session_path, method: 'delete' %></li>
            <% else %>
              <li><%= link_to 'Log in', new_user_session_path  %></li>
            <% end %> 
                      
          </ul>
          </div>
        </div>
      </div>
    </div>

    <div class="front-container container">
      <div class="row">
        <div class="col-lg-3">
          <!--sidebar start-->
          <aside>
              <div id="sidebar" class="nav-collapse md-box-shadowed">
                  <!-- sidebar menu start-->
                  <div class="leftside-navigation leftside-navigation-scroll" style="overflow: hidden; outline: none;" tabindex="5000">
                      <ul class="sidebar-menu" id="nav-accordion">
                        <% categories.each do |category| %>
                          <%= render :partial => "layouts/partials/tree", locals: {:category => category } %>
                        <% end %>
                      </ul>           
                  </div>
                  <!-- sidebar menu end-->
              
          </aside>    <!--sidebar end-->


        </div>
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2017</p>
      </footer>

    </div> <!-- /container -->

  
  <script type="text/javascript">


      $(document).ready(function(){
          new WOW().init();

          App.initPage();
          App.initLeftSideBar();
          
      });
  </script>


  </body>
</html>

app/views/layouts/dashboard.html.erb
<!DOCTYPE html>
<!-- saved from url=(0058)http://lancecoder.com/themes/thema/versions/html/index.php -->
<html lang="en" class="js mq no-touch gr__lancecoder_com"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="description" content="">
    <meta name="keywords" content="thema bootstrap template, thema admin, bootstrap, admin template, bootstrap admin">

    <meta name="author" content="LanceCoder">

    <title class="tooltipstered"><%= content_for?(:title) ? yield(:title) : "Inventory" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <%= javascript_include_tag "application" %>

    <!-- Just for debugging purposes. Don't actually copy this line! -->
    <!--[if lt IE 9]>
    <script src="js/ie8-responsive-file-warning.js"></script><![endif]-->
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
<style type="text/css">.jqstooltip { position: absolute;left: 0px;top: 0px;visibility: hidden;background: rgb(0, 0, 0) transparent;background-color: rgba(0,0,0,0.6);filter:progid:DXImageTransform.Microsoft.gradient(startColorstr=#99000000, endColorstr=#99000000);-ms-filter: "progid:DXImageTransform.Microsoft.gradient(startColorstr=#99000000, endColorstr=#99000000)";color: white;font: 10px arial, san serif;text-align: left;white-space: nowrap;padding: 5px;border: 1px solid white;z-index: 10000;}.jqsfield { color: white;font: 10px arial, san serif;text-align: left;}</style></head>


<body id="default-scheme" data-gr-c-s-loaded="true">

    <section id="container">

        <div class="pop-header" style="width: 100%; padding: 20px; position: fixed; background-color: rgb(45, 41, 41); color: rgb(255, 255, 255); z-index: 10000; font-size: 14px; text-align: center; font-weight: bold; display: none;">
            <span>Please check our new "Bootstrap Admin Template" here: <a href="https://goo.gl/tHPzXQ" target="_blank" style="color: #fff;">https://goo.gl/tHPzXQ</a>.</span>

            <span style="float: right; background: red; color: white; padding: 5px 10px; cursor: pointer;" class="close-pop-up">Close</span>
        </div>

        <%= render 'layouts/partials/header' %>

        <%= render 'layouts/partials/sidebar' %>

        

        <!--main content start-->
        <section id="main-content">

                
            <section class="wrapper">

                <%= render 'layouts/partials/breadcrumb' %>
                <%= bootstrap_flash %>
                <%= yield %>


            </section>
            
        </section>
        <!--======== Main Content End ========-->


        

    </section><!--/.container-->

   
    

    <script type="text/javascript">


        $(document).ready(function(){
            new WOW().init();

            App.initPage();
            App.initLeftSideBar();
            App.initCounter();
            App.initNiceScroll();
            App.initPanels();
            App.initProgressBar();
            App.initSlimScroll();
            App.initNotific8();
            App.initTooltipster();
            App.initStyleSwitcher();
            App.initMenuSelected();
            App.initRightSideBar();
            App.initEmail();
            App.initSummernote();
            App.initAccordion();
            App.initModal();
            App.initPopover();
            App.initOwlCarousel();
            App.initSkyCons();
            App.initWidgets();

            DashboardGreen.initRickShawGraph();
            DashboardGreen.initFlotGraph();
            DashboardGreen.initChartGraph();
            DashboardGreen.initSparklineGraph();
            DashboardGreen.initDateRange();
            DashboardGreen.initWorldMap();
            DashboardGreen.initEasyPieChart();
            DashboardGreen.initMorrisChart();
            DashboardGreen.initTodoList();

            if($.cookie("is_close_popup_header") === undefined || $.cookie("is_close_popup_header") != 1) {
                $(".pop-header").slideDown(1000);
            }

            $(".close-pop-up").on("click", function(){
                $.cookie("is_close_popup_header", 1);
                $(".pop-header").slideUp();
            });

        });
    </script>






<!--===== Footer End ========-->
</body>
</html>

app/views/layouts/partials/_breadcrumb.html.erb
<!--======== Page Title and Breadcrumbs Start ========-->
<div class="top-page-header">
    
    <div class="page-title">
        <h2>Thema Dashboard</h2>
        <small>Your admin dashboard.</small>
    </div>
    <div class="page-breadcrumb">
        <nav class="c_breadcrumbs">
            <ul>
                <li><a href="http://lancecoder.com/themes/thema/versions/html/index.php#">Thema</a></li>
                <li class="active"><a href="http://lancecoder.com/themes/thema/versions/html/index.php#">Dashboard</a></li>
            </ul>
        </nav>
    </div>
    <!-- <div class="right-menu pull-right">
        Reporting Period
        <div class="btn-group">
          <button data-toggle="dropdown" class="btn btn-default dropdown-toggle">Last 10 days <span class="caret"></span></button>
          <ul class="dropdown-menu bullet pull-middle animated pulse">
            <li>
              <input type="radio" id="ex1_1" name="ex1" value="1" checked="">
              <label for="ex1_1">Last 10 days</label>
            </li>
            <li>
              <input type="radio" id="ex1_2" name="ex1" value="2">
              <label for="ex1_2">Last 20 days</label>
            </li>
            <li>
              <input type="radio" id="ex1_3" name="ex1" value="3">
              <label for="ex1_3">Last 30 days</label>
            </li>
          </ul>
        </div>

    </div> -->

    <!-- <div class="pull-right toggle-right-sidebar">
        <span class="fa fa-outdent fa-2x title-open-right-sidebar tooltipstered"></span>
    </div> -->

</div>
<!--======== Page Title and Breadcrumbs End ========-->

app/views/layouts/partials/_cart_text.html.erb
<%= link_to "#{current_order.order_items.size} Items in Cart ( #{number_to_currency(current_order.subtotal, unit: 'TK', format: "%n %u")} )", cart_path, class: "btn btn-link" %>

app/views/layouts/partials/_sidebar.html.erb
<!--sidebar start-->
<aside>
    <div id="sidebar" class="nav-collapse md-box-shadowed">
        <!-- sidebar menu start-->
        <div class="leftside-navigation leftside-navigation-scroll" style="overflow: hidden; outline: none;" tabindex="5000">
            <ul class="sidebar-menu" id="nav-accordion">
                <li class="sidebar-profile">

                    <div class="profile-options-container">
                        <p class="text-right profile-options"><span class="profile-options-close pe-7s-close fa-2x font-bold"></span></p>

                        <div class="profile-options-list animated zoomIn">
                            <p><a href="http://lancecoder.com/themes/thema/versions/html/app-pages/page-profile-dashboard.html">Profile</a></p>
                            <p><a href="http://lancecoder.com/themes/thema/versions/html/app-pages/page-profile-settings.html">Settings</a></p>
                            <p><a href="javascript:void(0)">Help</a></p>
                            <p><a href="http://lancecoder.com/themes/thema/versions/html/app-pages/page-login-2.html">Log Out</a></p>
                        </div>
                        
                    </div>
                    
                    <div class="profile-main">
                        <p class="text-right profile-options"><i class="profile-options-open icon-options-vertical fa-2x"></i></p>
                        <p class="image">
                            <%= image_tag("profile.jpg", width: 80) %>

                            <span class="status"><i class="fa fa-circle text-success"></i></span>
                        </p>
                        <p>
                            <span class="name">John Doe</span><br>
                            <span class="position" style="font-family: monospace;">Administrator</span>
                        </p>
                    </div>
                    
                </li>
                <li class=" ">
                    <%= link_to(dashboard_path, class: "hvr-bounce-to-right-sidebar-parent #{active_class(dashboard_path)}") do  %>
                        <span class="fa fa-home fa-2x"></span><span>Dashboard</span>
                    <% end %>
                </li>
                <li>
                    <%= link_to(products_path, class: "hvr-bounce-to-right-sidebar-parent", "data-turbolinks" => "false") do  %>
                        <span class="icon-sidebar fa fa-product-hunt fa-2x"></span>
                        <span>Product</span>
                    <% end %>
                </li>
                <li>
                    <%= link_to(categories_path, class: "hvr-bounce-to-right-sidebar-parent") do  %>
                        <span class="icon-sidebar fa fa-sitemap fa-2x"></span>
                        <span>Category</span>
                    <% end %>
                </li>
                <li>
                    <%= link_to(setting_path, class: "hvr-bounce-to-right-sidebar-parent") do  %>
                        <span class="icon-sidebar fa fa-cogs fa-2x"></span>
                        <span>Setting</span>
                    <% end %>
                </li>
                <li>
                    <%= link_to(sales_path, class: "hvr-bounce-to-right-sidebar-parent") do  %>
                        <span class="icon-sidebar fa fa-tags fa-2x"></span>
                        <span>Sales</span>
                    <% end %>
                </li>
                <li class="sub-menu  dcjq-parent-li"><a href="http://lancecoder.com/themes/thema/versions/html/1" class="hvr-bounce-to-right-sidebar-parent dcjq-parent"><span class="icon-sidebar icon-screen-desktop fa-2x"></span><span>Layouts</span><span class="fa dcjq-icon"></span></a>
                    <ul class="sub" style="display: block;">
                        <li class="sub-menu dcjq-parent-li"><a href="javascript:void(0);" class="dcjq-parent">Boxed Page<span class="fa dcjq-icon"></span></a>
                            <ul class="sub" style="display: none;">
                                <li><a href="http://lancecoder.com/themes/thema/versions/html/layouts/boxed_page.html">Default</a>
                                </li>
                                <li><a href="http://lancecoder.com/themes/thema/versions/html/layouts/boxed_page_fixed_header.html">Default + Fixed Header</a>
                                </li>
                                <li><a href="http://lancecoder.com/themes/thema/versions/html/layouts/boxed_page_no_sidebar.html">No sidebar</a>
                                </li>
                                <li><a href="http://lancecoder.com/themes/thema/versions/html/layouts/boxed_page_no_sidebar_fixed_header.html">No sidebar + Fixed Header</a>
                                </li>
                            </ul>
                        </li>
                        <li><a href="http://lancecoder.com/themes/thema/versions/html/layouts/full_width_content.html">Full width content</a>
                        </li>
                        <li><a href="http://lancecoder.com/themes/thema/versions/html/layouts/blank.html">Blank Page</a>
                        </li>
                    </ul>
                </li>
                
           
            </ul>           
        </div>
        <!-- sidebar menu end-->
    <div id="ascrail2000" class="nicescroll-rails" style="width: 3px; z-index: auto; cursor: default; position: absolute; top: -18px; left: 237px; height: 605px; opacity: 0; display: block;"><div style="position: relative; top: 0px; float: right; width: 3px; height: 418px; background-color: rgba(76, 81, 86, 0.2); border: 0px solid rgb(255, 255, 255); background-clip: padding-box; border-radius: 0px;"></div></div><div id="ascrail2000-hr" class="nicescroll-rails" style="height: 3px; z-index: auto; top: 584px; left: 0px; position: absolute; cursor: default; display: none; width: 237px; opacity: 0;"><div style="position: relative; top: 0px; height: 3px; width: 240px; background-color: rgba(76, 81, 86, 0.2); border: 0px solid rgb(255, 255, 255); background-clip: padding-box; border-radius: 0px;"></div></div></div>
</aside>    <!--sidebar end-->




<!-- /menu footer buttons -->

<!--<div class="sidebar-footer hidden-small">
    <a class="tooltip-settings" title="Settings">
        <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
    </a>
    <a class="tooltip-fullscreen" title="Full Screen">
        <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
    </a>
    <a class="tooltip-resize-fullscreen" title="Resize Screen" style='display:none'>
        <span class="glyphicon glyphicon-resize-full" aria-hidden="true"></span>
    </a>
    <a class="tooltip-lock" title="Lock">
        <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
    </a>
    <a class="tooltip-logout" title="Logout">
        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
    </a>
</div>-->    <!-- /menu footer buttons -->

app/views/layouts/partials/_tree.html.erb
<li class="<%= category.children.count>0 ?  'sub-menu dcjq-parent-li' : '' %>">
    <%= link_to category_path(category), class: category.root? ? 'hvr-bounce-to-right-sidebar-parent dcjq-parent' : '', "data-turbolinks" => "false" do %>
        <span><%= category.title %></span>
        <% if category.children.count >0 %>
            <span class="fa dcjq-icon"></span>
        <% end %>
    <% end %>

    <% if category.children.count > 0 %>
        <ul class="sub" style="display: block;">
            <% for child in category.children do %>
                <%= render :partial => "layouts/partials/tree", :locals => {:category => child }%>
            <% end %>
        </ul>
    <% end %>
</li>

app/views/shared/_error.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul style="color: red">
    <% object.errors.full_messages.each do |msg| %>
      <li> <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>