config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: 'auth', path_names: { sign_in: 'login', sign_out: 'logout', registration: 'register', sign_up: 'cmon_let_me_in' }
  
  resources :orders, only: [:index, :update, :destroy]
  resource  :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]
  
  resources :categories do
    collection do
      post :rebuild
    end
  end

  resources :units
  resources :brands
  resources :products do
    resources :details
  end
  resources :sales


  
  root to: 'static#home'
  get '/dashboard' => 'static#dashboard'
  get '/setting'=>'static#setting'
  # get '/categories/:category' => 'static#products_by_category', as: 'products_by_category'
  
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord

  validates :name, presence: true
  has_many :product

end

app/models/category.rb
class Category < ApplicationRecord
	acts_as_nested_set
	extend FriendlyId
	friendly_id :title, use: :slugged

  	has_many :products
end

app/models/order.rb
class Order < ApplicationRecord
	has_many :order_items

	before_save :update_subtotal

  	def subtotal
    	order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
  	end
  
	private
	  def update_subtotal
	    self[:subtotal] = subtotal
	  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :unit_price, numericality: true, presence: true
  validate :product_present
  # validate :order_present

  before_save :finalize


  scope :today, lambda {where(created_at: Date.today.beginning_of_day..Date.today.end_of_day)}
  scope :current_week, lambda {where(created_at: Date.today.beginning_of_week.beginning_of_day..Date.today.end_of_week.end_of_day)}
  scope :last_week, lambda {where(created_at: Date.today.last_week.beginning_of_week.beginning_of_day..Date.today.last_week.end_of_week.end_of_day)}

  scope :current_month, lambda {where(created_at: Date.today.beginning_of_month.beginning_of_day..Date.today.end_of_month.end_of_day)}
  scope :last_month, lambda {where(created_at: Date.today.last_month.beginning_of_month.beginning_of_day..Date.today.last_month.end_of_month.end_of_day)}

  # scope :current_month_sales_rate, lambda {OrderItem.current_month.count*100/Product.sum(:quantity) if Product.sum(:quantity)>0}
  # scope :weekly_sales_rate_of_current_month, lambda {OrderItem.current_week.count*100/OrderItem.current_month.count if OrderItem.current_month.count>0}

  

  def self.current_month_sales_rate
    if Product.sum(:quantity)>0
      self.current_month.count*100/Product.sum(:quantity) 
    else
      0
    end
  end

  def self.weekly_sales_rate_of_current_month
    if OrderItem.current_month.count>0
      self.current_week.count*100/OrderItem.current_month.count 
    else
      0
    end
  end


  # @weekly_top_sales = OrderItem.current_week.group(:product_id).order('sum_quantity desc').sum(:quantity)
  #   @monthly_top_sales = OrderItem.current_month.group(:product_id).order('sum_quantity desc').sum(:quantity)


  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.unit_price
    end
  end

  def total_price
    unit_price * quantity
  end

	private
	  def product_present
	    if product.nil?
	      errors.add(:product, "is not valid or is not active.")
	    end
	  end

	  # def order_present
	  #   if order.nil?
	  #     errors.add(:order, "is not a valid order.")
	  #   end
	  # end

	  def finalize
	    self[:unit_price] = unit_price
	    self[:total_price] = quantity * self[:unit_price]
	  end
end

app/models/product.rb
class Product < ApplicationRecord
	belongs_to :category
	belongs_to :unit
	belongs_to :brand
	has_many :product_details, :dependent => :destroy
	has_many :order_items

	before_destroy :destroy_details

	extend FriendlyId
	friendly_id :name, use: :slugged

	validates :product_code, presence: true, uniqueness: true
	validates :name, presence: true
	validates :category_id, presence: true
	validates :unit_id, presence: true
	validates :brand_id, presence: true
	validates :unit_price, presence: true, numericality: true

	def self.search(search)
		where('name LIKE ? ', "%#{search}%")
	end

	def self.search_by_category(category, search)
		category.products.where('name LIKE ? ', "%#{search}%")
	end

	private
		def destroy_details
			self.product_details.delete_all
		end
end

app/models/product_detail.rb
class ProductDetail < ApplicationRecord
	belongs_to :product
	
	validates :quantity, presence: true
	validates :purchase_price, presence: true, numericality: true
end

app/models/unit.rb
class Unit < ApplicationRecord
	validates :name, presence: true
	has_many :product
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
  	@order_items = current_order.order_items
  end
end

app/controllers/details_controller.rb
class DetailsController < ApplicationController
	layout 'dashboard'
	before_action :set_product
	def index
		@product_details = @product.product_details
	end

	def new
		@detail = ProductDetail.new
	end

	def create
		@detail = ProductDetail.new(detail_params)
		@detail.previous_quantity = @product.quantity
		if @detail.save
			@product.quantity += @detail.quantity
			@product.save
			flash[:success] = "New product has been added!"
			redirect_to product_details_path
		else
			render "new"
		end
	end

	def destroy
		@detail = ProductDetail.find(params[:id])
		@product.quantity = @product.quantity - @detail.quantity
		@product.save
		@detail.destroy
		flash[:danger] = "Item has been deleted successfully!"
		redirect_to product_details_path
	end

	private
		def detail_params
			params.require(:product_detail).permit(:product_id, :purchase_price, :previous_quantity, :quantity)
		end

		def set_product
			@product = Product.friendly.find(params[:product_id])
		end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def active_class(link_path)
	  current_page?(link_path) ? "active" : ""
	end

	def categories
	  @categories = Category.roots
	end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products/details_helper.rb
module Products::DetailsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/details/_form.html.erb
<%= form_for @detail, :html => {:class => "form-horizontal"} do |f| %>
	<div class="form-group has-success">
		<div class="col-md-6 col-md-offset-3">
			<%= render 'shared/error', object: f.object %>
		</div>
	</div>
	<%= f.hidden_field :product_id, value: @product.id %>

	<div class="form-group has-success">
		<%= f.label :quantity, "Quantity", class: "col-md-3 control-label" %>
	    <div class="col-md-6">
	        <%= f.text_field :quantity, class: "form-control" %>
	    </div>
	</div>	

	<div class="form-group has-success">
		<%= f.label :purchase_price, "Purchase Price", class: "col-md-3 control-label" %>
	    <div class="col-md-6">
	        <%= f.text_field :purchase_price, class: "form-control" %>
	    </div>
	</div>

	<div class="form-group">
        <div class="col-lg-offset-3 col-lg-6">
        	<%= f.submit "Save", class: "btn btn-primary btn-md" %>
        </div>
    </div>


<% end %>

app/views/details/index.html.erb
<div class="row">
  <div class="col-md-12 col-sm-12 col-xs-12">
    <div class="widget">
      <div class="widget-header bg-white">
          <h3 class="fg-gray"><%= @product.name %> Details <span class="badge bg-color label-danger"><%= @product.quantity %></span></h3>
          <%= link_to new_product_detail_path(@product) do %>
            <span class="fa fa-plus fg-gray pull-right btn-todo-add"></span>
          <% end %>
          <div class="clearfix"></div>
      </div>
      <div class="widget-content bg-white">
          <table class="table  table-hover general-table" id="product-details-table">
            <thead>
              <tr>
                <th>Previous Quantity</th>
                <th>New Quantity</th>
                <th>Purchase Price</th>
                <th>Action</th>
              </tr>
            </thead>
            <tbody>
				<% @product_details.each do |item| %>
					<tr>
						<td><%= item.previous_quantity %></td>
						<td><%= item.quantity %></td>
						<td><%= item.purchase_price %></td>
            <td>
              <%= link_to(fa_icon('trash-o lg'), product_detail_path(@product, item), :method => :delete, data: {:confirm => 'Are you sure?'}) %>
                
            </td>
					</tr>
				<% end %>
            </tbody>
          </table>
      </div><!--/widget-content--> 
    </div><!--/widget-->
  </div>
</div>

app/views/details/new.html.erb
<div class="row">

    <div class="col-md-12">
        
        <!--=========== START TAGS INPUT ===========-->
        

        <div class="c_panel">

            <div class="c_title">
                <h2>Add More Product</h2>
                <div class="clearfix"></div>
            </div><!--/.c_title-->

            <div class="c_content">

                <%= render "form" %>
                
                
            </div><!--/.c_content-->

        </div><!--/.c_panels-->

    </div>

</div>